const ON_SEARCH_PHOTOS_ENTER = 'ON_SEARCH_PHOTOS_ENTER'
const ON_INITIAL_PHOTOS_LOADED = 'ON_INITIAL_PHOTOS_LOADED'
const ON_LOAD_MORE_PHOTOS = 'ON_LOAD_MORE_PHOTOS'
const ON_MORE_PHOTOS_LOADED = 'ON_MORE_PHOTOS_LOADED'

export {
  ON_SEARCH_PHOTOS_ENTER,
  ON_INITIAL_PHOTOS_LOADED,
  ON_LOAD_MORE_PHOTOS,
  ON_MORE_PHOTOS_LOADED
}